In [142]:
import nltk
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem import WordNetLemmatizer
import string
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

In [41]:
Science_fiction = 0
Horror = 1
Adventure = 2
Humor = 3
Western = 4
Mystery = 5
Gothic = 6


In [4]:
nltk_stop_words = nltk.corpus.stopwords.words('english')

In [19]:
f = open("set0/western01.txt", "r")
western1 = f.read()

In [45]:
f = open("set0/gothic00.txt", "r")
gothic1 = f.read()

In [102]:
def remove_gutenberg_preamble(text):
    try:
        return text[text.index("***", text.index("START OF THIS PROJECT GUTENBERG"))+3:]
    except:
        return text[text.index("***", text.index("START OF THE PROJECT GUTENBERG"))+3:]

In [119]:
def remove_gutenberg_postscript(text):
    try:
        return text[:text.index("***", text.index("END OF THE PROJECT GUTENBERG"))-3]
    except:
        return text[:text.index("***", text.index("END OF THIS PROJECT GUTENBERG"))-3]

In [22]:
western1 = remove_gutenberge_preamble(western1)

In [23]:
tokens = word_tokenize(western1)

In [29]:
tokens = [t for t in tokens if t not in string.punctuation]

In [32]:
tokens = [t for t in tokens if t not in nltk_stop_words]

In [33]:
len(tokens)

83640

In [178]:
wordnet_lemmatizer = WordNetLemmatizer()
# vectorizing function to able to call on list of tokens
lemmatize_words = np.vectorize(wordnet_lemmatizer.lemmatize)
lemmatized_text = ' '.join(lemmatize_words(tokens))

In [40]:
text_clf = Pipeline([
    ('vect', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('clf', MultinomialNB()),
])

In [54]:
text = [western1, remove_gutenberge_preamble(gothic1)]
target = [Western, Gothic]

In [55]:
text_clf.fit(text, target)

Pipeline(steps=[('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('clf', MultinomialNB())])

In [69]:
text_clf.predict_proba(["By de name Jim Crow Dat de white folk call If ever I see I 'tends maul Just"])

array([[0.49969613, 0.50030387]])

training by feeding in the entire book seems to be counter productive since the model cannot be decisive

In [82]:
# lets try splitting by \n
f = open("set0/gothic00.txt", "r")
gothic1 = f.read()
gothic1 = remove_gutenberge_preamble(gothic1)

In [83]:
arr = gothic1.split('\n\n')


In [84]:
arr = [a for a in arr if len(a) > 2]


In [85]:
df = pd.DataFrame()
df['text'] = arr

In [86]:
df['label'] = Gothic

In [100]:
df[len(df)-51:]

text  label
1525  \n*** END OF THE PROJECT GUTENBERG EBOOK THE P...      6
1526  ***** This file should be named 174-0.txt or 1...      6
1527  Updated editions will replace the previous one...      6
1528  Creating the works from print editions not pro...      6
1529                                START: FULL LICENSE      6
1530  THE FULL PROJECT GUTENBERG LICENSE\nPLEASE REA...      6
1531  To protect the Project Gutenberg-tm mission of...      6
1532  Section 1. General Terms of Use and Redistribu...      6
1533  1.A. By reading or using any part of this Proj...      6
1534  1.B. "Project Gutenberg" is a registered trade...      6
1535  1.C. The Project Gutenberg Literary Archive Fo...      6
1536  1.D. The copyright laws of the place where you...      6
1537  1.E. Unless you have removed all references to...      6
1538  1.E.1. The following sentence, with active lin...      6
1539    This eBook is for the use of anyone anywhere...      6
1540  1.E.2. If an individual Project Gutenberg-tm e...      6
1541  1.E.3. If an individual Project Gutenberg-tm e...      6
1542  1.E.4. Do not unlink or detach or remove the f...      6
1543  1.E.5. Do not copy, display, perform, distribu...      6
1544  1.E.6. You may convert to and distribute this ...      6
1545  1.E.7. Do not charge a fee for access to, view...      6
1546  1.E.8. You may charge a reasonable fee for cop...      6
1547  * You pay a royalty fee of 20% of the gross pr...      6
1548  * You provide a full refund of any money paid ...      6
1549  * You provide, in accordance with paragraph 1....      6
1550  * You comply with all other terms of this agre...      6
1551  1.E.9. If you wish to charge a fee or distribu...      6
1552                                               1.F.      6
1553  1.F.1. Project Gutenberg volunteers and employ...      6
1554  1.F.2. LIMITED WARRANTY, DISCLAIMER OF DAMAGES...      6
1555  1.F.3. LIMITED RIGHT OF REPLACEMENT OR REFUND ...      6
1556  1.F.4. Except for the limited right of replace...      6
1557  1.F.5. Some states do not allow disclaimers of...      6
1558  1.F.6. INDEMNITY - You agree to indemnify and ...      6
1559  Section 2. Information about the Mission of Pr...      6
1560  Project Gutenberg-tm is synonymous with the fr...      6
1561  Volunteers and financial support to provide vo...      6
1562  Section 3. Information about the Project Guten...      6
1563  The Project Gutenberg Literary Archive Foundat...      6
1564  The Foundation's business office is located at...      6
1565  Section 4. Information about Donations to the ...      6
1566  Project Gutenberg-tm depends upon and cannot s...      6
1567  The Foundation is committed to complying with ...      6
1568  While we cannot and do not solicit contributio...      6
1569  International donations are gratefully accepte...      6
1570  Please check the Project Gutenberg web pages f...      6
1571  Section 5. General Information About Project G...      6
1572  Professor Michael S. Hart was the originator o...      6
1573  Project Gutenberg-tm eBooks are often created ...      6
1574  Most people start at our website which has the...      6
1575  This website includes information about Projec...      6

In [101]:
def get_label(file_loc: str) -> int:
    science_fiction = 0
    horror = 1
    adventure = 2
    humor = 3
    western = 4
    mystery = 5
    gothic = 6
    if 'gothic' in file_loc:
        return gothic
    if 'western' in file_loc:
        return western
    if 'mystery' in file_loc:
        return mystery
    if 'humor' in file_loc:
        return humor
    if 'adventure' in file_loc:
        return adventure
    if 'horror' in file_loc:
        return horror
    if 'scifi' in file_loc:
        return science_fiction

In [112]:
def create_by_newline(file_loc: str, df):
    new_df = pd.DataFrame()
    f = open(file_loc, "r")
    text = f.read()
    text = remove_gutenberg_preamble(text)
    text = remove_gutenberg_postscript(text)
    arr = text.split('\n\n')
    arr = [a for a in arr if len(a) > 2]
    label = get_label(file_loc)
    new_df['text'] = arr
    new_df['label'] = label
    df = df.append(new_df)
    return df

In [113]:
new_df = pd.DataFrame()

In [114]:
new_df = create_by_newline('set0/gothic00.txt',new_df)

In [116]:
new_df = create_by_newline('set0/gothic01.txt',new_df)

In [120]:
new_df = create_by_newline('set0/western00.txt', new_df)

In [122]:
text_clf.fit(new_df.text, new_df.label)

Pipeline(steps=[('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('clf', MultinomialNB())])

In [130]:
text_clf.predict([' brother he certainly was, in the eye of the law, and it is more than probable that he was his brother in reality. But thelaird thought otherwise; and, though he knew and acknowledged that hewas obliged to support and provide for him, he refused to acknowledge'])

array([4])

In [131]:
train_on = [
    'set0/western00.txt',
    'set0/western01.txt',
    'set0/western02.txt',
    'set0/western03.txt',
    'set0/gothic00.txt',
    'set0/gothic01.txt',
    'set0/gothic02.txt',
    'set0/gothic03.txt',
    'set0/humor00.txt',
    'set0/humor01.txt',
    'set0/humor02.txt',
    'set0/humor03.txt',
    'set0/horror00.txt',
    'set0/horror01.txt',
    'set0/horror02.txt',
    'set0/horror03.txt',
]

In [133]:
new_df = pd.DataFrame()
for file in train_on:
    new_df = create_by_newline(file, new_df)

In [135]:
text_clf.fit(new_df['text'], new_df['label'])

Pipeline(steps=[('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('clf', MultinomialNB())])

In [140]:
text_clf.predict_proba(['Immediately subsequent to this disaster, my father seemed nearly in'])

array([[0.16330431, 0.42661755, 0.22499629, 0.18508185]])

text  label
0               \nProduced by Bill Brewer and Rick Fane      4
1                             RIDERS OF THE PURPLE SAGE      4
2                                          By Zane Grey      4
3                                 \nCHAPTER I. LASSITER      4
4     A sharp clip-crop of iron-shod hoofs deadened ...      4
...                                                 ...    ...
2069  When we got home we got to talking of the old ...      1
2070  “We want no proofs; we ask none to believe us!...      1
2071                                 /Jonathan Harker./      1
2072  End of the Project Gutenberg EBook of Dracula,...      1
2073      *** END OF THIS PROJECT GUTENBERG EBOOK DRACU      1

[28464 rows x 2 columns]

In [149]:
X_train, X_test, y_train, y_test = train_test_split(new_df['text'], new_df['label'], 
                                                    random_state=42, stratify=new_df['label'])

In [157]:
text_clf.fit(X_train, y_train)

Pipeline(steps=[('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('clf', MultinomialNB())])

In [171]:
arr = np.array(y_test)
arr

array([4, 1, 6, ..., 6, 4, 3])

In [176]:
def check_accuracy(classifier, X_test, y_test):
    y_test_arr = np.array(y_test)
    correct = 0
    for i, item in enumerate(X_test):
        res = classifier.predict([item])
        if(res == arr[i]):
            correct += 1
    print('Accuracy: ' + str(correct/X_test.shape[0] * 100))

In [177]:
check_accuracy(text_clf, X_test, y_test)

Accuracy: 66.83530073074762
